// Generated by CoffeeScript 1.7.1
var module;

module = angular.module('ngIndeterminateCheckbox', []);

module.directive('indeterminate', function() {
  return {
    restrict: 'A',
    link: function(scope, element, attributes) {
      return scope.$watch(attributes.indeterminate, function(val) {
        return element.prop('indeterminate', !!val);
      });
    }
  };
});
